version: '3'

services:
    mongo:
        image: mongo:bionic
        ports:
            - "27017-27019:27017-27019"
        volumes:
            - mongo-config:/data/configdb
            - mongo-db:/data/db
        container_name: mongo
        restart: always

    tradelog:
        build: .
        image: tradelog:latest
        ports:
            - "8080:8080"
            - "8443:8443"
        environment:
            - DB_URL=${DB_URL}
            - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            - GOOGLE_DISCOVERY_URL=${GOOGLE_DISCOVERY_URL}
        container_name: tradelog
        restart: always

    nginx:
        container_name: nginx
        image: nginx:stable
        restart: always
        ports:
            - "80:80"

volumes:
    mongo-config:
    mongo-db:
